### ISSUE TITLE
 AWS CloudHSM (Cavium LiquidSecurity FIPS PCIe Card) - hourly signing procedure cost

### ISSUE THREAD

**Issue by bneiluj** [tacoinfra/remote-signer#13]
What is the implied daily cost of receiving messages from the Tezos baking client and passing them on to a remote HSM to be signed on AWS CloudHSM based on the number of daily required Tezos baking signatures? AWS charges a total hourly price per HSM roughly between $1.45 - $2 based on geographic locations.

**Comment by lyoungblood** [comment]
Hi @bneiluj in order to bake with a CloudHSM, you need to run it 24/7, so the monthly cost is at least the hourly cost multiplied by the number of hours in a month. If you want high availability, you can choose to run 2 CloudHSMs in a cluster, which will double the cost.

Each CloudHSM can do a few hundred signatures per second, so performance is not a concern. Tezos typically only requires signatures to be generated at most 2x per minute (once for baking when producing a block and once for endorsing a block).
